### ISSUE TITLE
Edit profile feature

### ISSUE THREAD

**Issue by xmclark** [tranhungt/okcupidjs#13]
Add methods for editing one's profile essays and details This could be broken up into pieces.

**Comment by tranhungt** [comment]
Nice.

**Comment by jwjames83** [comment]
I have a commit for the details. I've yet to do the details, but it's just as simple. Pull request in the next few days.

**Comment by tranhungt** [comment]
Feature built: https://github.com/tranhungt/okcupidjs/pull/22
