### ISSUE TITLE
OKCupid.js Example Code Request 

### ISSUE THREAD

**Issue by RTHyman** [tranhungt/okcupidjs#15]
What I'm hoping you could do is provide me (or point me to the link with the code if it exists ... but I cant find it) with some of your basic code lines so I can make use of at least a few of the methods so I can learn enough to pick up some speed. I've spent at least 10-20 hours poring over this project and another 10-20 learning javascript and I've hit a wall. 

In case its helpful here's what I've got so far:

function callback(err, res, body) {
  if (!err) { console.log(res) }
}

var OKCupid = require('okcupidjs');

var okc = new OKCupid();

okc.login("myactualusername", "myrealpassword", callback);

okc.getVisitors(callback);

okc.getRecentMessages(callback);

okc.sendMessage("randomuser", "Hello", callback);

I can't login to send a message, when I look at the HTTP I can pull data about other users but it all comes back as [object] as I don't know the right command to pull the relevant data to the console.

If you could help me out really quickly with some example code I'm really thinking it will help jumpstart me.

**Comment by jwjames83** [comment]
Instead of console.log (res), try console.log (body) and inspect the result.

Since you need to login first before doing anything else you should put getVisitors, getRecentMessages, etc. within the callback..except, I'd have separate callbacks for each function (sendMessageCallback, getVisitorsCallback, etc.)

**Comment by gnutix** [comment]
I too think that some examples in the doc would be nice. :)

**Comment by tranhungt** [comment]
@gnutix, @RTHyman 
Here is a quick sample. I can add this to the docs.
```
var OKCupid = require('okcupidjs')
var okc = new OKCupid()

okc.login('okc_username/email', 'okc_password', function(err, res, body) {
    okc.getQuickmatch(function(err, res, body) {
        okc.like(body.tuid);
    }
})    
```

**Comment by gnutix** [comment]
@tranhungt Thanks for the example. I've just tried with this code below but get an HTML output (and not JSON) : 

```
var OKCupid = require('okcupidjs');
var okc = new OKCupid();

okc.login('xxxx', 'yyyy', function() {
    okc.getQuickmatch(function(err, res, body) {
        console.log(body);
    });
});
```

**Comment by xmclark** [comment]
@gnutix, @tranhungt  it is possible that the quickmatch api changed or we were always getting HTML from that request. It should certainly be possible to get the data back as json. 

I could validate this issue over the weekend sometime.

**Comment by tranhungt** [comment]
@gnutix @xmclark I just tried the getQuickmatch method and it works for me. I'm using latest version.

**Comment by tranhungt** [comment]
@gnutix 
Try to put the `err, res, response` params in your login callback and print the parameters to see if you were actually authenticated properly. An unexpected HTML is usually a symptom of bad authentication.
```
okc.login('xxxx', 'yyyy', function(err, res, body) {
    console.log(err);
    okc.getQuickmatch(function(err, res, body) {
        console.log(body);
    });
});
```

**Comment by xmclark** [comment]
@gnutix @tranhungt so I just tried it and it does seem that the getQuickmatch returns HTML. If I add the ?okc_api=1 parameter to the URL, I can get the quickmatch query in JSON. It might be worth updating the target URL for quickmatch so the okcupidjs stays consistent with JSON APIs.

**Comment by xmclark** [comment]
Took me like seven months, but I did write an issue for adding the extra option to the endpoint in #26. 

I recommend closing this issue.
