### ISSUE TITLE
Document search paging

### ISSUE THREAD

**Issue by xmclark** [tranhungt/okcupidjs#17]
Search allows one to make queries for users on OKC. The API has a paging feature so the server does not have to send large json objects back on each query. I believe this design decision made sense for OKC at the time.

The documentation only briefly points out the page hashes returned from the search method, but it is not clear how to use them. A new section should be added to the README that describes paging in a little more detail, and a usage example should be added the samples section.

**Comment by xmclark** [comment]
@tranhungt I'm putting together the document describing search paging. Do you think a search with paging example should be put into a separate markdown file that is linked to from the README.md (i.e. SEARCH.md)? Or would you prefer all samples to live in README.md?

**Comment by tranhungt** [comment]
Hey Mackenzie. Thanks for doing this. I think a separate markdown with link will be helpful, so you don't feel constrained be the lengthiness of the original readme.

Thanks!

**Comment by tranhungt** [comment]
Resolved https://github.com/tranhungt/okcupidjs/pull/19
