### ISSUE TITLE
async/await

### ISSUE THREAD

**Issue by josephdburdick** [tranhungt/okcupidjs#20]
Hey, this is a fun project, thanks for your work. I was wondering with the way you've structured the callbacks after ever method, is there a way to pull off async/await instead? 

Thanks in advance.

**Comment by tranhungt** [comment]
Hm, it would probably require a separate module to wrap all the existing calls. I'd welcome any PR though.

**Comment by xmclark** [comment]
The first logical step towards async functions would be promisifying the library. I know of a handful of libraries that can take a callback type function and make a promise, but I think you're suggesting refactoring the library.

@tranhungt, I'm not too familiar with exposing the same API with different paradigms (callbacks and promises) in the same module. I naturally want to reach for namespaces...alas Js does not have them. Objects will have to do.

This is what first came to mind:
```
var okc = new require('okcupidjs').CallbackApi()
var okcAsync = new require('okcupidjs').AsyncApi()
```

Thoughts?

**Comment by tranhungt** [comment]
@xmclark I'm not familiar with how to promisify the library. Do you have any examples of libraries you're thinking of?
The examples of the API you give looks good.
We can also provide backwards compatibility where `new require('okcupidjs')` will default to `CallbackApi()`.

**Comment by xmclark** [comment]
@tranhungt [this is what I'm referring to.](http://bluebirdjs.com/docs/features.html#promisification-on-steroids)

Libraries like bluebird.js can take a promise-unaware library and make it promisified. This may actually be our preferred suggestion because it doesn't require us to change the API. 
```javascript
var OKCupid = require('okcupidjs');
var Promise = require('bluebird');

var okc = Promise.promisifyAll(new OKCupid());

// all async OKCupid methods have the method name + "Async", e.g. okc.loginAsync(...)
okc.loginAsync("xmclark", "my-pass").then((done) => {console.log("done!")});
```

**Comment by tranhungt** [comment]
@xmclark Wow that's awesome! Thanks for finding this! So it's up to the user to use this library, or something else they prefer, and we won't need to change anything in our code, other than mentioning this in the documentation if anyone wants to use it.

**Comment by xmclark** [comment]
@tranhungt I was waiting for you to make the call on this. I think that is a great idea. I will make a PR.

**Comment by xmclark** [comment]
See #23. I did a little maintenance on that section of the readme so that the comments made sense.

**Comment by tranhungt** [comment]
Thanks @xmclark. I've merged the PR and published to NPM.

Thanks!
