### ISSUE TITLE
Is there a more detailed version on how to use this?

### ISSUE THREAD

**Issue by LVG5Pelican** [tranhungt/okcupidjs#21]
I keep getting ECONNRESET error in the err of send message..

    okc.search(query, (err, res, body) => {
        if (err) {
            console.log("Failed to get search results.");
        }
        else {
            // use the body object to extract the search results
            var results = body.data;
            results.forEach((user)=> {
                    //console.log(user.username + '\n');
                    okc.sendMessage(user.id, message_body, (err, res, body) => {
                            var messageResults = err;
                            console.log(messageResults);
                            console.log('Message sent to:\n');
                            console.log(user.username + '\n');
                        }
                    )
                }
            );

            //console.log('Users:\n')
        }
    });

**Comment by xmclark** [comment]
@LVG5Pelican Can you isolate which method is throwing the error? Are you sure you have logged in correctly?

If I had to take a guess, I'd say it is coming out of `okc.sendMessage` but can't tell for sure.

**Comment by tranhungt** [comment]
@LVG5Pelican I would go through the response of each call and make sure that the data you're parsing out is what you think it is, in case there are some uncaught errors.
For example, is `body.data` or `user.id` parsing out correctly?
And is `message_body` instantiated somewhere up top?

**Comment by xmclark** [comment]
There has been no discussion on this issue. I recommend closing it. We can re-open it later, if there is more feedback.
