### ISSUE TITLE
node-uuid@1.4.8 is deprecated warning

### ISSUE THREAD

**Issue by xmclark** [tranhungt/okcupidjs#24]
When running `npm install okcupidjs --save`, the following warning is printed:
`npm WARN deprecated node-uuid@1.4.8: Use uuid module instead`

This package is a dependency of the request module. The warning goes away if the project is upgrades request from version `2.40.0` to `>=2.83.0`.

**Comment by xmclark** [comment]
I created a login and basic search test with okcupidjs using the updated request module. A more rigorous test could be made, but I think that is good enough. Everything worked as expected.

**Comment by tranhungt** [comment]
Thanks @xmclark. I'll update and push it later today. Thanks for testing it out.

**Comment by xmclark** [comment]
@tranhungt I wasn't doing anything and I had it staged already, so I just went ahead and made pr #25  😄
