### ISSUE TITLE
.rate() returns 302 redirect to /login

### ISSUE THREAD

**Issue by JamesHenry** [tranhungt/okcupidjs#3]
Hi @tranhungt,

I am not sure if this is because OkCupid have changed their API since you last worked on this, but I seem to always get a 302 redirect back from the rate() method. When enabling request redirects to be followed I see it is the returning the login HTML.

Any thoughts?

Best,

James

**Comment by tranhungt** [comment]
Hi @JamesHenry,

It could be that you have not been properly logged in yet, so you keep getting the redirect to the login HTML.

Is it happening only on the rate() function?
Have you tried other function calls?

More generally speaking, an API change would generally give a more obvious error codes, like a 301 permanently moved, or a 404 not found. But it would be curious if that was the case, since these endpoints are officially supported.

Let me know!

**Comment by tranhungt** [comment]
@JamesHenry , I'm going to assume this helped.
Feel free to re-open if you're still having trouble.

**Comment by JamesHenry** [comment]
Apologies, @tranhungt - bad issue form from me! Busy week!

Yes, other methods seem to work. I was just trying to write a simple getQuickmatch then rate sequence and the getQuickmatch works as expected, but the rate call seems to redirect me to login as I mentioned.

Interestingly I am not sure the concept of rating exists on OkCupid anymore (at least not in the UK), but when doing a little inspecting on the site I can see that the call to match (swipe right) is essentially a fixed rate (POST to /quickmatch with score: 4

**Comment by xmclark** [comment]
Perhaps this method should be deprecated, and a new `likeUser` method should be added?

I did an inspection and it seems for a like the score is **4** and a dislike it is a **0** and another random field called "cant_tell"" is set to **1**.

**Comment by tranhungt** [comment]
@xmclark Yeah, it's very possible that OKC changed their endpoints.

**Comment by xmclark** [comment]
I actually think they kept the same endpoint, but just only use two values in the enumeration. 

It feels a bit shaky though. If I were developing this feature, it would feel kind of hacky to me. I wonder if they will change the endpoint anytime soon. I did notice that in their UI, they renamed "Quickmatch" to "DoubleTake", but still use the same endpoint `/quickmatch`.

**Comment by tranhungt** [comment]
Well I supposed OKC isn't really known to have the best engineering in the world. I've dug into their API's before and there was a bunch of personal information being passed around.
But maybe they just don't care. It works for them, I guess.

**Comment by tranhungt** [comment]
@xmclark so it seems like we only need to update the documentation for this one?

**Comment by xmclark** [comment]
Yes I think so. Or a new method for liking users that takes a bool instead of an int. True for like, false for dislike. It would use the same endpoint though. If you're interested in this, I can make a PR.

**Comment by tranhungt** [comment]
Sounds good. Yeah, a new endpoint for like/dislike would be good.

A PR would be much appreciated. Thanks @xmclark.

**Comment by xmclark** [comment]
PR #9 addresses this problem.

**Comment by tranhungt** [comment]
PR #9  has been merged, which should fix this issue. Please Reopen if you're still experiencing issues.
