### ISSUE TITLE
"questions": filter working properly?

### ISSUE THREAD

**Issue by Petenks** [tranhungt/okcupidjs#35]
Apologies if this is an oversight on my part, but I have been experimenting with the .search method and it seems the method can (seemingly randomly) overlook certain users when returning results with the  "questions":  filter on.

For example, I ran a test of all users around my location with a certain question/answer combo using both okucupidjs and the OKCupid site itself. The website returned far more users than the API, which only snagged a portion of them. I've been reviewing the users and checking my code to see if I could figure out what's going on, but I can't seem to find any reason for why the API returns certain users and ignores others.

Here is the base query and search method in my tests:

> var base_query = {
>     "i_want": "women", 
>     "minimum_age": 18,
>     "maximum_age": 30, 
>     "questions": [302], 
>     "answers": [2],  
>     radius: 10 
> };
> 
> function search(okc, query, count) {
>     okc.search(query, function (err, res, body) { 
>         body.data.forEach(function (user) {
>             console.log(user.username); 
>             console.log("=============="); 
>         }); 
>         var hash = body.paging.cursors.after; 
>         if (hash != null && count <= 1) { 
>             query.after = hash; 
>             newCount = count + body.data.length; 
>             search(okc, query, newCount);
>         }
>     });
> }

Apologies again if I have overlooked something, but it seems my searches continuously return only a portion of the users the actual OKC site finds. Even when I increase my radius, while the number of returned users goes up, it does not match the number returned by OKC. Is there a reason for this?

As a follow-up, is there possibly a Discord channel I can look into for help with okcupidjs? Thanks.

**Comment by xmclark** [comment]
> it seems the method can (seemingly randomly) overlook certain users when returning results with the "questions": filter on.
If I recall correctly, the search results come in pages. See this page that I spend way too much time writing: https://github.com/tranhungt/okcupidjs/blob/master/SEARCH.md

> As a follow-up, is there possibly a Discord channel I can look into for help with okcupidjs? Thanks.
The project does not have a presence but I would be up for making one 😄 . Would you be fine with slack? I prefer slack.

**Comment by Petenks** [comment]
Yes, I used the example from that page as the basis for my code, but as soon as I add the "questions/answer" filters it causes issues.

Here is the 'first 100' example you provided; the only changes I have made is adding the filters: 

```
var base_query = { i_want: "women", they_want: "men", "questions": [309], "answers": [2], radius: 25 };

function search(okc, query, count) {
    okc.search(query, function (err, res, body) {
        // print out usernames
        body.data.forEach(function (user) {
            console.log(user.username);
        });

        // get next page with "after" cursor
        var hash = body.paging.cursors.after;

        // check termination condtion, otherwise recurse
        if (hash != null && count <= 100) {
            // get the query with the next hash
            query.after = hash;
            // increase the count
            newCount = count + body.data.length;
            // recursively call the search function
            search(okc, query, newCount);
        }
    });
}

var OKCupid = require('okcupidjs');
var okc = new OKCupid();

```
This returns the following error in relation to the body.data.forEach(function (user):

> TypeError: Cannot read property 'data' of undefined

Seems like it may be going out of bounds? I'm not exactly sure what's happening or why adding a filter would cause this considering the vanilla 100 search works just fine.

Slack works fine, though I think Discord would get more traffic. Let me know when it's up regardless! 

Thanks for your help!

**Comment by xmclark** [comment]
It's going to be a couple days before I can dig into this, so I apologize.

But I was able to make a slack channel.
okcupidjs.slack.com

Feel free to join!

**Comment by Petenks** [comment]
No worries, just follow-up here when you crack it. =)

Also, it seems I need an invite to join the Slack channel.

**Comment by xmclark** [comment]
@Petenks see the new invite link  https://publicslack.com/slacks/okcupidjs/invites/new
it is also in the readme now

**Comment by xmclark** [comment]
I think this issue was captured in another issue. Closing this for now.
