### ISSUE TITLE
Search Example: Repeating Same User 

### ISSUE THREAD

**Issue by Petenks** [tranhungt/okcupidjs#38]
Using the Search Example provided combined with the Questions/Answers filter example directly from the main okcupidjs GH page (q 403/a 2) returns the same group of users several times before the program completes. 

Tested the questions-filter with a more specific question and yeah, it will repeat the same sole-user it found several-dozen times; seems it's repeating its findings again and again for some reason.

**Comment by Petenks** [comment]
I tested this solution and found that only a small portion of the qualifying-users are caught by the API:

const baseQuery = {i_want: "men", they_want: "women" , radius: 10, "questions": [309], "answers": [2] };

OKCupid Website found 24 users,
okcupidjs found only 5.

**Comment by xmclark** [comment]
I was missing a very important line `baseQuery.after = hash;`. This was crucial to how the API works.

**Comment by xmclark** [comment]
Changes have been merged to master.
