### ISSUE TITLE
Send / Receive messages 

### ISSUE THREAD

**Issue by luizs81** [tranhungt/okcupidjs#4]
Hello!
Are there in this wrapper methods to read and send messages?

**Comment by tranhungt** [comment]
Hi there,

Not at the current time. Feel free to send a pull request, that would be much appreciated.

**Comment by xmclark** [comment]
@tranhungt I did some poking, and it looks like sending messages can be solved using the OAuth token. I've put together a simple solution, and it needs some tinkering. 

I think this ticket could be re-opened for sending messages. Getting the inbox may be a little more hacky though.

**Comment by tranhungt** [comment]
@xmclark Sounds good. Thanks for your interest in tinkering. :)

**Comment by tranhungt** [comment]
We now have support for receiving/sending messages. Thanks to @xmclark.
This ticket will now be closed.
