### ISSUE TITLE
question about the structure of the requests

### ISSUE THREAD

**Issue by obiwankenoobi** [tranhungt/okcupidjs#43]
Lovely library! Source code look so good! Great job. I wondered, how did you knew the structure of the requests okc need? i.e here for example: 

```
    var login_form = {
      okc_api: 1,
      username: username,
      password: password,
    };
``` 

How did you investigated the way it should be sent? Thanks!

**Comment by xmclark** [comment]
Hello @obiwankenoobi ! Thank you for the compliment! The way we did is not super fancy. We inspect the requests and responses that are sent/received when we perform operations in the okcupid app. It requires using the dev tools in the browser and inspecting payloads. There was also some good guess work done.

**Comment by obiwankenoobi** [comment]
@xmclark love it. Any idea if okc has some spam filter? I mean, if I am now sending messages to 100 people, how am I not being blocked? ( I did it and it went so well it was weird lol )

**Comment by xmclark** [comment]
@obiwankenoobi great question. In my experience with the API, there is not much blocking. I have not attempted to do that...so maybe they do have some kind of filter, but I doubt it.
