### ISSUE TITLE
Cannot read property 'oauth_accesstoken' of undefined

### ISSUE THREAD

**Issue by baderth** [tranhungt/okcupidjs#44]
was working for some time, now errors at:

_/node_modules/okcupidjs/lib/client.js:26
      else if (body.oauth_accesstoken) {
                    ^
TypeError: Cannot read property 'oauth_accesstoken' of undefined_

**Comment by xmclark** [comment]
We may have overstayed our welcome...

Did you have a chance to inspect the body? They may have moved the `oauth_accesstoken` member, or renamed it.

**Comment by baderth** [comment]
its working again, changed nothing...
