### ISSUE TITLE
login returns false positive

### ISSUE THREAD

**Issue by xmclark** [tranhungt/okcupidjs#7]
Calling the `OKCupid.prototype.login` method will not populate the error object because a 200 status is always returned. 

If an incorrect password is entered, I will get a false positive. I would expect the error object to populated with the error string. 

A few examples:

```js
var OKCupid = require('okcupidjs')
var okc = new OKCupid()
okc.login("fake_username", "some_password", (err, res, body) => {...}) // error is empty
okc.login("valid_username", "some_password", (err, res, body) => {...}) // error is empty
okc.login("valid_username", "", (err, res, body) => {...}) // error is empty
```

**Comment by xmclark** [comment]
If the project is interested in this fix, I have the changes locally and can make a PR.

**Comment by tranhungt** [comment]
Hi @xmclark,
Thanks for bringing this up. Sure, I'd gladly accept your PR. It will help others looking to use this library as well.

**Comment by xmclark** [comment]
Wow, quick reply. Thanks for being so open to changes. 

I've used git before, but this will be my **first** pull request. Do you have any style preferences for the commit messages or pull requests?

**Comment by tranhungt** [comment]
No specific style preferences. The PR looks good.
I'll close this.

https://github.com/tranhungt/okcupidjs/pull/8
